version: 2
executorType: machine
stages:
  build:
    parallel: 1
    workDir: ~/st2-packages
    environment:
      - DISTROS: trusty xenial el6 el7 wheezy jessie
      - ST2_PACKAGES: st2 st2mistral
    steps:
      - type: checkout
      - type: shell
        name: Stop Default Services
        command: |
          sudo service postgresql stop
          sudo service mongod stop
          sudo service rabbitmq-server stop
      - type: shell
        name: Show Docker versions
        command: |
          docker --version
          docker-compose --version
      - type: shell
        name: Initialize Build Environment
        command: |
          .circle/buildenv_st2.sh
          .circle/buildenv_mistral.sh
      - type: shell
        name: Pull Images
        command: |
          . ~/.buildenv
          .circle/docker-compose.sh pull ${DISTRO}
      - type: shell
        name: Build Packages
        command: |
          . ~/.buildenv
          .circle/docker-compose.sh build ${DISTRO}
      - type: shell
        name: Test Packages
        command: |
          . ~/.buildenv
          .circle/docker-compose.sh test ${DISTRO}
