version: 2
executorType: machine
stages:
  build:
    steps:
      - type: checkout
      - type: shell
        name: Verify Docker Works
        command: |
          docker --version
          docker run hello-world
