version: 2
executorType: machine
stages:
  build:
    parallel: 1
    workDir: ~/st2-packages
    steps:
      - type: checkout
      - type: shell
        name: Show Docker versions
        command: |
          docker --version
          docker-compose --version
