version: 2
executorType: machine
stages:
  build:
    parallel: 1
    workDir: ~/st2-packages
    steps:
      - type: checkout
      - type: shell
        name: Show Docker versions
        command: |
          docker --version
          docker-compose --version
      - type: shell
        name: Pull Images
        command: |
          .circle/docker-compose.sh pull trusty
      - type: shell
        name: Build Packages
        command: |
          .circle/docker-compose.sh build trusty
      - type: shell
        name: Test Packages
        command: |
          .circle/docker-compose.sh test trusty
