trusty:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=trustybuild
    - TESTNODE=trustytest
  links:
    - trustybuild
    - trustytest
    - rabbitmq
    - mongodb
    - postgres

xenial:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=xenialbuild
    - TESTNODE=xenialtest
  links:
    - xenialbuild
    - xenialtest
    - rabbitmq
    - mongodb
    - postgres

bionic:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=bionicbuild
    - TESTNODE=bionictest
  links:
    - bionicbuild
    - bionictest
    - rabbitmq
    - mongodb
    - postgres

el7:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - BUILDNODE=centos7build
    - TESTNODE=centos7test
  links:
    - centos7build
    - centos7test
    - rabbitmq
    - mongodb
    - postgres

el6:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-compose
  environment:
    - ST2_PYTHON=1
    - BUILDNODE=centos6build
    - TESTNODE=centos6test
  links:
    - centos6build
    - centos6test
    - rabbitmq
    - mongodb
    - postgres

## Package build nodes
#
trustybuild:
  image: stackstorm/packagingbuild:trusty
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

xenialbuild:
  image: stackstorm/packagingbuild:xenial
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

bionicbuild:
  image: stackstorm/packagingbuild:bionic
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

centos6build:
  image: stackstorm/packagingbuild:centos6
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

centos7build:
  image: stackstorm/packagingbuild:centos7
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

## Package testing nodes
#
trustytest:
  image: stackstorm/packagingtest:trusty-upstart
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

xenialtest:
  image: stackstorm/packagingtest:xenial-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-compose
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

bionictest:
  image: stackstorm/packagingtest:bionic-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-compose
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

centos6test:
  image: stackstorm/packagingtest:centos6-sshd
  extends:
    file: docker-compose.override.yml
    service: volumes-compose

centos7test:
  image: stackstorm/packagingtest:centos7-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-compose
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
