trusty:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-circle
  environment:
    - BUILDNODE=trustybuild
    - TESTNODE=trustytest
  links:
    - trustybuild
    - trustytest

xenial:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-circle
  environment:
    - BUILDNODE=xenialbuild
    - TESTNODE=xenialtest
  links:
    - xenialbuild
    - xenialtest

el7:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-circle
  environment:
    - BUILDNODE=centos7build
    - TESTNODE=centos7test
  links:
    - centos7build
    - centos7test

el6:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: docker-compose.override.yml
    service: suite-circle
  environment:
    - ST2_PYTHON=1
    - BUILDNODE=centos6build
    - TESTNODE=centos6test
  links:
    - centos6build
    - centos6test

## Package build nodes
#
trustybuild:
  image: stackstorm/packagingbuild:trusty
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

xenialbuild:
  image: stackstorm/packagingbuild:xenial
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

centos6build:
  image: stackstorm/packagingbuild:centos6
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

centos7build:
  image: stackstorm/packagingbuild:centos7
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

## Package testing nodes
#
trustytest:
  image: stackstorm/packagingtest:trusty-upstart
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

xenialtest:
  image: stackstorm/packagingtest:xenial-systemd
  privileged: true
  extends:
    file: docker-compose.override.yml
    service: volumes-circle
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

centos6test:
  image: stackstorm/packagingtest:centos6-sshd
  extends:
    file: docker-compose.override.yml
    service: volumes-circle

centos7test:
  image: stackstorm/packagingtest:centos7-systemd
  extends:
    file: docker-compose.override.yml
    service: volumes-circle
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
